export const CHANGE_MODAL_STATUS = "CHANGE_MODAL_STATUS";
export const CHANGE_SUCCESS_MODAL_STATUS = "CHANGE_SUCCESS_MODAL_STATUS";
export const POST_FORM_DATA = "POST_FORM_DATA";
export const LOADING = "LOADING";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
